---
- name: Setup Xen on Ubuntu
  become: true
  hosts: all
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
    - setup: # aka gather_facts
  tasks:
    - name: Update & upgrade
      apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
    - name: Remove Guest Additions
      apt:
        name: virtualbox-guest-dkms
        state: absent
        autoremove: yes
    - name: Install Xen
      apt:
        pkg: '{{ item }}'
        state: present
      with_items:
        - git
        - golang
        - qemu-system-x86
        - vim
        - xen-hypervisor
    - name: Reboot into Xen
      shell: 'sleep 2 && shutdown -r now "Ansible updates triggered"'
      async: 1
      poll: 0
      ignore_errors: yes
    - name: Wait for server to come back
      local_action: wait_for host="{{ inventory_hostname }}"
      args:
        state: started
        delay: 10
      become: false
